/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <seven_segment_display.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

#include "stm32f407xx.h"
#include "scheduler.h"
#include "buttons.h"




int main(void)
{
	initSchedulerStack(SHEDULER_STACK_START);

	addTaskHandlers();

	initButtons();
	initDisplay();

	initTasksStack();

	//initGpio

	//main function and ISR use MSP as stack pointer, lets switch to PSP
	switchSPtoPSP();

	task1Handler();

    /* Loop forever */
	for(;;);
}



void task1Handler(void)
{
	while(1)
	{
		for(int i = 0; i<50000;i++)
		{
			setDigitOnDisplay(1);
		}

		for(int i = 0; i<50000;i++)
		{
			setDigitOnDisplay(9);
		}
	}
}

void task2Handler(void)
{
	while(1)
	{
		for(int i = 0; i<50000;i++)
		{
			setDigitOnDisplay(2);
		}

		for(int i = 0; i<50000;i++)
		{
			setDigitOnDisplay(8);
		}
	}
}

void task3Handler(void)
{
	while(1)
	{
		for(int i = 0; i<50000;i++)
		{
			setDigitOnDisplay(3);
		}

		for(int i = 0; i<50000;i++)
		{
			setDigitOnDisplay(7);
		}
	}
}
