/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <seven_segment_display.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

#include "stm32f407xx.h"
#include "scheduler.h"
#include "buttons.h"
#include "systick.h"


int main(void)
{
	initSchedulerStack(SHEDULER_STACK_START);

	initTasks();

	initButtons();

	initDisplay();

	initSysTick(1);

	//main function and ISR use MSP as stack pointer, lets switch to PSP
	switchSPtoPSP();

	startCounterSysTick();

	task1Handler();

    /* main should not reach this point  */
	for(;;);
}


void task1Handler(void)
{
	while(1)
	{
		setDigitOnDisplay(1);
		while(isSysTickFinishedCounting() == 0);
		setDigitOnDisplay(9);
		while(isSysTickFinishedCounting() == 0);
	}
}

void task2Handler(void)
{
	while(1)
	{
		setDigitOnDisplay(2);
		while(isSysTickFinishedCounting() == 0);
		setDigitOnDisplay(8);
		while(isSysTickFinishedCounting() == 0);
	}
}

void task3Handler(void)
{
	while(1)
	{
		setDigitOnDisplay(3);
		while(isSysTickFinishedCounting() == 0);
		setDigitOnDisplay(7);
		while(isSysTickFinishedCounting() == 0);
	}
}
